// AUTO-GENERATED by digital_journal/index.py - do not edit.
// Run: bash refresh.sh to regenerate.
window.__MANIFEST = {"generated_at": "", "generator_version": "0.1", "projects": {}, "all_tags": []};
